import{a as M,S as q,i as p}from"./assets/vendor-CldWAlh7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function i(r){if(r.ep)return;r.ep=!0;const a=s(r);fetch(r.href,a)}})();const S="52905819-433962418f10cc5e4a65a61ca",u=15,B=M.create({baseURL:"https://pixabay.com/api/",timeout:1e4,params:{key:S,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function v(e,t=1,s=u){const{data:i}=await B.get("",{params:{q:e,page:t,per_page:s}});return i}function w({page:e,perPage:t=u,totalHits:s}){return e*t<s}function P(e){return e.map(({webformatURL:t,largeImageURL:s,tags:i,likes:r,views:a,comments:l,downloads:d})=>`
<li class="photo-card">
  <a class="gallery__link" href="${s}">
    <img class="gallery__image" src="${t}" alt="${_(i)}" loading="lazy" />
  </a>
  <ul class="info">
    <li><span>Likes</span><b>${r}</b></li>
    <li><span>Views</span><b>${a}</b></li>
    <li><span>Comments</span><b>${l}</b></li>
    <li><span>Downloads</span><b>${d}</b></li>
  </ul>
</li>`).join("")}function H(e){e.innerHTML=""}function E(e,t){t&&e.insertAdjacentHTML("beforeend",t)}function m(e){e.classList.remove("is-hidden")}function c(e){e.classList.add("is-hidden")}function g(e,t=!0){e.disabled=t,e.setAttribute("aria-busy",String(t))}function f(e,t=""){e.textContent=t}function _(e=""){return e.replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[t])}function $(e){p.success({message:e,position:"topRight",timeout:2500})}function y(e){p.info({message:e,position:"topRight",timeout:3e3})}function h(e){p.error({message:e,position:"topRight",timeout:3500})}let o={},n={query:"",page:1,totalHits:0,isLoading:!1},L;document.addEventListener("DOMContentLoaded",()=>{var e;if(o={form:document.querySelector("form.form")||document.querySelector("#search-form"),input:document.querySelector("#query"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector("#load-more"),loader:document.querySelector(".loader"),message:document.querySelector("#message")},L=new q(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),o.loadMoreBtn&&c(o.loadMoreBtn),o.loader&&c(o.loader),!o.form){console.error('Form element not found. Add class="form" or id="search-form".');return}o.form.addEventListener("submit",x),(e=o.loadMoreBtn)==null||e.addEventListener("click",O)});async function x(e){e.preventDefault();const t=o.input.value.trim();if(n.query=t,n.page=1,n.totalHits=0,f(o.message,""),c(o.loadMoreBtn),H(o.gallery),!t){h("Please enter a search term.");return}await b()}async function O(){await b(!0)}async function b(e=!1){if(!n.isLoading)try{n.isLoading=!0,g(o.loadMoreBtn,!0),m(o.loader);const t=await v(n.query,n.page,u),{hits:s,totalHits:i}=t;if(n.totalHits=i,s.length===0&&n.page===1){y("No images found for your search query."),c(o.loadMoreBtn);return}n.page===1&&$(`Found ${i} images.`);const r=P(s);if(E(o.gallery,r),L.refresh(),w({page:n.page,perPage:u,totalHits:n.totalHits})?m(o.loadMoreBtn):(c(o.loadMoreBtn),f(o.message,"We're sorry, but you've reached the end of search results."),y("You've reached the end of search results.")),e){const l=document.querySelector(".gallery .photo-card");if(l){const{height:d}=l.getBoundingClientRect();window.scrollBy({top:d*2,behavior:"smooth"})}}n.page+=1}catch(t){console.error(t),f(o.message,"Unexpected error. Please try again later."),h("Unexpected error. Please try again later.")}finally{n.isLoading=!1,c(o.loader),g(o.loadMoreBtn,!1)}}
//# sourceMappingURL=index.js.map
