import{a as y,S as h}from"./assets/vendor-BQwYM3kP.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const a of document.querySelectorAll('link[rel="modulepreload"]'))i(a);new MutationObserver(a=>{for(const o of a)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(a){const o={};return a.integrity&&(o.integrity=a.integrity),a.referrerPolicy&&(o.referrerPolicy=a.referrerPolicy),a.crossOrigin==="use-credentials"?o.credentials="include":a.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(a){if(a.ep)return;a.ep=!0;const o=s(a);fetch(a.href,o)}})();const b="52905819-433962418f10cc5e4a65a61ca",d=15,L=y.create({baseURL:"https://pixabay.com/api/",timeout:1e4,params:{key:b,image_type:"photo",orientation:"horizontal",safesearch:!0}});async function q(t,e=1,s=d){const{data:i}=await L.get("",{params:{q:t,page:e,per_page:s}});return i}function M({page:t,perPage:e=d,totalHits:s}){return t*e<s}function S(t){return t.map(({webformatURL:e,largeImageURL:s,tags:i,likes:a,views:o,comments:l,downloads:f})=>`
<li class="photo-card">
  <a class="gallery__link" href="${s}">
    <img class="gallery__image" src="${e}" alt="${P(i)}" loading="lazy" />
  </a>
  <ul class="info">
    <li><span>Likes</span><b>${a}</b></li>
    <li><span>Views</span><b>${o}</b></li>
    <li><span>Comments</span><b>${l}</b></li>
    <li><span>Downloads</span><b>${f}</b></li>
  </ul>
</li>`).join("")}function B(t){t.innerHTML=""}function w(t,e){e&&t.insertAdjacentHTML("beforeend",e)}function p(t){t.classList.remove("is-hidden")}function c(t){t.classList.add("is-hidden")}function g(t,e=!0){t.disabled=e,t.setAttribute("aria-busy",String(e))}function u(t,e=""){t.textContent=e}function P(t=""){return t.replace(/[&<>"']/g,e=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[e])}const r={form:document.querySelector("#search-form"),input:document.querySelector("#query"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector("#load-more"),loader:document.querySelector("#loader"),message:document.querySelector("#message")};let n={query:"",page:1,totalHits:0,isLoading:!1};const v=new h(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});c(r.loadMoreBtn);c(r.loader);r.form.addEventListener("submit",H);r.loadMoreBtn.addEventListener("click",_);async function H(t){t.preventDefault();const e=r.input.value.trim();if(n.query=e,n.page=1,n.totalHits=0,u(r.message,""),c(r.loadMoreBtn),B(r.gallery),!e){u(r.message,"Please enter a search term.");return}await m()}async function _(){await m(!0)}async function m(t=!1){if(!n.isLoading)try{n.isLoading=!0,g(r.loadMoreBtn,!0),p(r.loader);const e=await q(n.query,n.page,d),{hits:s,totalHits:i}=e;if(n.totalHits=i,s.length===0&&n.page===1){u(r.message,"Sorry, there are no images matching your search query."),c(r.loadMoreBtn);return}const a=S(s);if(w(r.gallery,a),v.refresh(),M({page:n.page,perPage:d,totalHits:n.totalHits})?p(r.loadMoreBtn):(c(r.loadMoreBtn),u(r.message,"We're sorry, but you've reached the end of search results.")),t){const l=document.querySelector(".gallery .photo-card");if(l){const{height:f}=l.getBoundingClientRect();window.scrollBy({top:f*2,behavior:"smooth"})}}n.page+=1}catch(e){console.error(e),u(r.message,"Unexpected error. Please try again later.")}finally{n.isLoading=!1,c(r.loader),g(r.loadMoreBtn,!1)}}
//# sourceMappingURL=index.js.map
